name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: walletconnect
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          docker version
          docker swarm init 2> /dev/null || true
      - run: make ci
      - name: "Pushes nix store to cachix nix cache"
        if: success()
        run: make cachix
        env:
           CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Print logs
        if: failure()
        run: docker service logs --tail 200 walletconnect_caddy && docker service logs --tail 200 walletconnect_relay
